// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package repository

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one

INSERT INTO rooms (key)
VALUES ($1)
RETURNING key, is_active
`

func (q *Queries) CreateRoom(ctx context.Context, key string) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, key)
	var i Room
	err := row.Scan(&i.Key, &i.IsActive)
	return i, err
}
